### ISSUE TITLE
Different results on Linux and Windows

### ISSUE THREAD

**Issue by bitcanvas** [MarcBT/grunt-grock#3] opened 2017-05-11 11:11 UTC
Hi Marc,

I have two Build server set up for Continuous Integration. On server is based on Linux, the other one on Windows. With both I generate a JavaScript documentation using grock. The output of the two servers is different. On Linux everything is fine but on Windows the folder structure is missing.
The problem might be in the generated toc.js. The generation uses the system file separator. So in correct generation (Linux) the paths look like:
```
"path": "src/js/asseteditor.js.html",
"originalName": "asseteditor.js",
"originalPath": "src/js/asseteditor.js", 
```
The files generated with the Windows server looks like:
```
"path": "src\\js\\asseteditor.js.html",
"originalName": "asseteditor.js",
"originalPath": "src\\js\\asseteditor.js",
```
Because it is JavaScript the path separator should always be “/”. Otherwise the logic for generating the navigation on the web pages should be able to interpret “\\”  and “\”.
Is there the possibility to fix this problem or get around?

Kind regard Matthias

**Comment by MarcBT** [comment] 2017-05-15 04:53
Hi Matthias ! (and sorry for the late answer).

`grunt-grock` is just a simple wrapper of `grock` which handles the documentation generation, so I guess `grock` repository is a better place to ask for this issue.
To confirm this , what's the generated toc.js file looks like when you directly use `grock` CLI instead of `grunt-grock` ?

Have a good day, 
Regards,
Marc

**Comment by MarcBT** [comment] 2017-05-15 05:16
I've gone through `grock` source and it looks like indeed you're right, file path is not converted to URL scheme before being used [inside html template](https://github.com/killercup/grock/blob/master/styles/solarized/assets/js/behavior.coffee#L102).

I guess the conversion step can be added here (https://github.com/killercup/grock/blob/master/lib/transforms/renderTemplates.coffee#L26
) as following but I did not tested it.

```
file.path = file.path.replace( /\\/g, '/' ) + ".html"
```
The `/\\/g` regex may be adapted to also manage whitespaces (you can check this jsfiddle: http://jsfiddle.net/StephenLujan/r6DYy/ ).

I hope it can help,
See you !

**Comment by MarcBT** [comment] 2017-05-17 16:45
@bitcanvas Moving to done as conclusion is that the issue is at `grock` project level.

**Closed as completed** 2017-05-17 16:46 UTC
